version: '2.27'

networks:
  dev:
    driver: bridge

services:
  webapi:
    image: docker.io/library/wenapi
    depends_on:
      - "app_db"
    container_name: wenapi-services
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=postgres; IntegratedSecurity=true;Pooling=true;  
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lip/postgresql/data
    networks:
      - dev
volumes:
  app_data: 
     
